# MVD 6. cvičení

## 1. část - PageRank

Data k dnešnímu cvičení použijte z tohoto [Github repozitáře](https://github.com/chonyy/PageRank-HITS-SimRank/tree/master/dataset). Konkrétně nás budou zajímat soubory *graph_1.txt* až *graph_6.txt*. K daným datasetům je v repozitáři implementace PageRank algoritmu, každopádně se touto implementací nijak neinspirujte. 

Cílem je naprogramovat PageRank vektorizovaně podle přednášky, povoleno je pouze použití knihovny numpy. Parametr $\alpha$ nastavte na hodnotu 0.2 a počet iterací bude 100. U prvních grafů uvidíte, že PageRank konverguje mnohem dříve a u těch složitějších nemusí stačit ani 100 iterací.

$
p^{(0)} = (\frac{1}{N}, ..., \frac{1}{N})^T \\
A = ((1-\alpha)M + \frac{\alpha}{N}E) \\
Opakujte: \\
\hspace{1cm}p^{(i+1)} = A^Tp^{(i)}
$

$A$ ... matice pravděpodobnosti přechodu

Pozor: Stránka, která nemá výstupní linky, musí mít nastavený parametr $\alpha$ na 1.

In [1]:

import numpy as np

#graph_1.txt
N_OF_FILES = 6
FOLDER="data"
FILE="graph_"
FORM=".txt"

### Load Data:

In [2]:
def parse_file(file_path):
    with open(file_path, 'r') as file:
        edges = []
        dim = 0
        for line in file.readlines():
            if len(list(line)) > 3:
                v_from, v_to = line.split(',')
                v_from = int(v_from)
                v_to = int(v_to)
                edges.append((v_from, v_to))
                if v_to > dim:
                    dim = v_to
                elif v_from > dim:
                    dim = v_from
    return edges, dim

def generate_M(edges, size, adjacency=False):
    M = np.zeros((size, size))
    for edge in edges:
        v_from, v_to = edge
        M[v_from-1, v_to-1] = 1
    if not adjacency:
        count = np.sum(M, axis=1).reshape(-1,1)
        indexes = (np.sum(M, axis=1) == 0).nonzero()
        count[indexes] = 1
        M /= count
    return M

def init_p(N):
    return 1/N * np.ones((N,1))

def init_A(M, N, alfa):
    alfas = alfa * np.ones((N,1))
    indexes = (np.sum(M, axis=1) == 0).nonzero()
    alfas[indexes] = 1
    return (1-alfa)*M + alfas/N * np.ones((N,N))

In [3]:
file_path = "data/graph_1.txt"

edges, N = parse_file(file_path)
print("Dim:", N)
print(edges)

Dim: 6
[(1, 2), (2, 3), (3, 4), (4, 5), (5, 6)]


In [67]:
M = generate_M(edges, N)
print(M)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


In [4]:
alfa=0.2

p = init_p(N)
print(p)
A = init_A(M,N,alfa)
print(A)

[[0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]
 [0.16666667]]


NameError: name 'M' is not defined

### Page Rank:

In [63]:
iterations = 100
alfa=0.2

for i in range(1, N_OF_FILES+1):
    file_path = FOLDER + '/' + FILE + str(i) + FORM
    print("File:", file_path)
    #print("    Loading.... ", end = '')
    edges, N = parse_file(file_path)
    M = generate_M(edges, N)
    p = init_p(N)
    A = init_A(M,N,alfa)
    #print("\t Done.")
    AT = A.T
    for j in range(iterations):
        p = np.matmul(AT,p)
    print(p)
    print()
    

File: data/graph_1.txt
[[0.0656044 ]
 [0.11808792]
 [0.16007474]
 [0.19366419]
 [0.22053575]
 [0.242033  ]]

File: data/graph_2.txt
[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]

File: data/graph_3.txt
[[0.17857143]
 [0.32142857]
 [0.32142857]
 [0.17857143]]

File: data/graph_4.txt
[[0.27257372]
 [0.15666713]
 [0.13837881]
 [0.10924643]
 [0.18531604]
 [0.06563464]
 [0.07218322]]

File: data/graph_5.txt
[[0.00163995]
 [0.00163995]
 [0.00163995]
 [0.00163995]
 [0.00163995]
 [0.00185861]
 [0.00177115]
 [0.00182737]
 [0.00196794]
 [0.00196794]
 [0.00182737]
 [0.00177115]
 [0.00196794]
 [0.00196794]
 [0.00177115]
 [0.00169711]
 [0.00170178]
 [0.0019428 ]
 [0.00198014]
 [0.00169465]
 [0.00365343]
 [0.003554  ]
 [0.00169465]
 [0.00402315]
 [0.00182136]
 [0.00185236]
 [0.00187664]
 [0.00170178]
 [0.00170178]
 [0.00240599]
 [0.00197445]
 [0.00175037]
 [0.00246671]
 [0.00225534]
 [0.00253521]
 [0.00193072]
 [0.00178986]
 [0.00168645]
 [0.00169465]
 [0.004043  ]
 [0.00170178]
 [0.00169465]
 [0.00369723]
 [

### Předpokládaný výstup

#### graph_1.xt
```python
array([[0.0656044 ],
       [0.11808792],
       [0.16007474],
       [0.19366419],
       [0.22053575],
       [0.242033  ]])
```
       
#### graph_2.txt
```python
array([[0.2],
       [0.2],
       [0.2],
       [0.2],
       [0.2]])
```


#### graph_3.txt
```python
array([[0.17857143],
       [0.32142857],
       [0.32142857],
       [0.17857143]])
```


#### graph_4.txt
```python
array([[0.27257372],
       [0.15666713],
       [0.13837881],
       [0.10924643],
       [0.18531604],
       [0.06563464],
       [0.07218322]])
```


## 2. část - HITS

Použijte stejná data jako u PageRank algoritmu a počet iterací bude opět 100.

Implementujte dle následujícího algoritmu:
<br>

$
a^{(0)} = (1, ..., 1)^T, h^{(0)} = (1, ..., 1)^T
\\
Opakujte:\\
    \hspace{1cm} h^{(i+1)} = Aa^{(i)}\\
    \hspace{1cm} h^{(i+1)} = \frac{h^{(i+1)}}{||h^{(i+1)}||_1}\\
    \hspace{1cm} a^{(i+1)} = A^Th^{(i)}\\
    \hspace{1cm} a^{(i+1)} = \frac{a^{(i+1)}}{||a^{(i+1)}||_1}\\
$

$A$ ... matice sousednosti

Použijte L1 normu.

In [5]:
def normalization(vec):
    return vec / np.linalg.norm(vec, ord=1)

In [6]:
iterations = 100
alfa=0.2

for i in range(1, N_OF_FILES+1):
    file_path = FOLDER + '/' + FILE + str(i) + FORM
    print("File:", file_path)
    edges, N = parse_file(file_path)
    A = generate_M(edges, N, adjacency=True)
    #print(A)
    h = np.ones((N,1))
    a = np.ones((N,1))
    AT = A.T
    for j in range(iterations):
        h_new = np.matmul(A,a)
        a_new = np.matmul(AT,h)
        h = normalization(h_new)
        a = normalization(a_new)
        
    print(a.T)
    print(h.T)
    print()

File: data/graph_1.txt
[[0.  0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2 0. ]]

File: data/graph_2.txt
[[0.2 0.2 0.2 0.2 0.2]]
[[0.2 0.2 0.2 0.2 0.2]]

File: data/graph_3.txt
[[0.19098301 0.30901699 0.30901699 0.19098301]]
[[0.19098301 0.30901699 0.30901699 0.19098301]]

File: data/graph_4.txt
[[0.13948389 0.17791203 0.20082321 0.14017775 0.20142536 0.05608926
  0.08408849]]
[[0.27545318 0.04776231 0.10868324 0.19865956 0.1837346  0.11673471
  0.06897241]]

File: data/graph_5.txt
[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
  0.00000000e+000 2.61604965e-057 2.68924599e-027 3.52327050e-047
  3.86356655e-086 3.86356655e-086 3.52327050e-047 2.68924599e-027
  3.86356655e-086 3.86356655e-086 2.68924599e-027 1.47000504e-003
  2.98870217e-046 4.92980706e-003 2.63006533e-048 1.08947980e-036
  1.97060198e-030 2.33388958e-030 1.08947980e-036 2.84750347e-030
  3.36694340e-003 2.81200455e-057 2.60018320e-057 2.98870217e-046
  2.98870217e-046 3.43153644e-101 5.89834577e-049 2.6

### Předpokládaný výstup

#### graph_1.xt
```python
Authority:[[0. ]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]
Hub: [[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0. ]]
```
       
#### graph_2.txt
```python
Authority:[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]
Hub: [[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]]
```


#### graph_3.txt
```python
Authority:[[0.19098301]
 [0.30901699]
 [0.30901699]
 [0.19098301]]
Hub: [[0.19098301]
 [0.30901699]
 [0.30901699]
 [0.19098301]]
```


#### graph_4.txt
```python
Authority:[[0.13948389]
 [0.17791203]
 [0.20082321]
 [0.14017775]
 [0.20142536]
 [0.05608926]
 [0.08408849]]
Hub: [[0.27545318]
 [0.04776231]
 [0.10868324]
 [0.19865956]
 [0.1837346 ]
 [0.11673471]
 [0.06897241]]
```


## Bonus - Invertovaný index pomocí MapReduce

Bonusovou úlohou je vytvoření invertovaného indexu stejně, jako je uvedeno na příkladu v přednášce. Implementace nebude v standardním MapReduce frameworku, ale použijete python funkce ```map()``` a ```reduce()```. Funkci map lze poté spustit paralelně s pomocí ```Pool``` objektu z knihovny ```multiprocessing```. 

Vstupními daty budou Medium články, které jsme používali v posledních pár cvičeních. Z těchto článků použijte pouze nadpisy (title). 

In [7]:
import csv
import json
import spacy
import string
import numpy as np
import multiprocessing
from multiprocessing_mapreduce import SimpleMapReduce

/home/pytel/.local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [9]:
file_path = "data/articles.csv"
lemmatizer = spacy.load('en_core_web_sm', disable=['parser', 'ner'])

/home/pytel/.local/lib/python3.10/site-packages/spacy/language.py:1895: UserWarning: [W123] Argument disable with value ['parser', 'ner'] is used instead of ['senter'] as specified in the config. Be aware that this might affect other components in your pipeline.
  warnings.warn(


In [10]:
with open(file_path, 'r') as read_obj:
    dict_reader = csv.DictReader(read_obj)
    data_raw = list(dict_reader)

In [22]:
def purge_chars(text, chars_to_remove):
    for c in list(chars_to_remove):
        text = text.replace(c, "")
    return text

def prep_text(text):
    # Převést všechen text na lower case
    text = text.lower()
    # Odstranění interpunkce a všech speciálních znaků (apostrof, ...)
    numbers = "1234567890"
    interpunction = ",.:;?!"
    chars = numbers + interpunction + '#^&@$€Łłþ→ø%+*/|\–—-\'’‘""”[]{}()'
    text = purge_chars(text, chars)
    # remove white spaces
    text = ' '.join(text.split())
    # Aplikace lemmatizátoru:
    return ' '.join([token.lemma_ for token in lemmatizer(text)])

def process_data(data):
    """
    data :
    [[Title, Text], ...] ->
    [[title, [word, ...]], ...]
    """
    ret = np.empty([len(data),2], dtype=object)
    for index, article in enumerate(data_raw):
        ret[index, 0] = prep_text(article["title"])
        ret[index, 1] = prep_text(article["text"])
    return ret

def split_to_word_lists(texts):
    return [text.split(' ') for text in texts]

def make_reverse_indexing(texts):
    words_indexes = {}
    word_lists = split_to_word_lists(texts)

def map_articels(data_raw):
    documents = process_data(data_raw)
    titles = documents[:,0]
    texts = documents[:,1]
    return enumerate(split_to_word_lists(titles))

def reduce_to_idf(index_and_word_list):
    for index, words_list in index_and_word_list:
        #print(words_list)
        for word in words_list:
            indexes = words_indexes.get(word, [])
            indexes.append(index)
            words_indexes[word] = indexes
            #print("words_indexes[", word, "] ->", indexes)
    return words_indexes

In [23]:
documents = process_data(data_raw)
titles = documents[:,0]
texts = documents[:,1]

In [32]:
from collections import Counter
from itertools import chain
from functools import reduce

In [81]:
def count_words_in_title(atr) -> dict:
    index, text = atr
    counted = dict(Counter(text.split(" ")))
    words = {}
    for key in counted:
        words[key] = ("D"+str(index), counted[key])
    return words

def join_dicts(dict1: dict, dict2: dict) -> dict:
    for word in dict2:
        words_in_first = dict1.get(word, [])
        words_in_first.append(dict2[word])
        dict1[word] = words_in_first
    return dict1

In [86]:
words = list(map(
    count_words_in_title,
    enumerate(titles)
))
words.insert(0, dict())
words

[{},
 {'chatbots': ('D0', 1),
  'be': ('D0', 1),
  'the': ('D0', 2),
  'next': ('D0', 1),
  'big': ('D0', 1),
  'thing': ('D0', 1),
  'what': ('D0', 1),
  'happen': ('D0', 1),
  'startup': ('D0', 1),
  'medium': ('D0', 1)},
 {'python': ('D1', 1),
  'for': ('D1', 1),
  'datum': ('D1', 1),
  'science': ('D1', 1),
  'concept': ('D1', 1),
  'you': ('D1', 1),
  'may': ('D1', 1),
  'have': ('D1', 1),
  'forget': ('D1', 1)},
 {'automate': ('D2', 1),
  'feature': ('D2', 1),
  'engineering': ('D2', 1),
  'in': ('D2', 1),
  'python': ('D2', 1),
  'towards': ('D2', 1),
  'data': ('D2', 1),
  'science': ('D2', 1)},
 {'machine': ('D3', 1),
  'learn': ('D3', 1),
  'how': ('D3', 1),
  'to': ('D3', 2),
  'go': ('D3', 1),
  'from': ('D3', 1),
  'zero': ('D3', 1),
  'hero': ('D3', 1),
  'freecodecamp': ('D3', 1)},
 {'reinforcement': ('D4', 1),
  'learning': ('D4', 1),
  'from': ('D4', 1),
  'scratch': ('D4', 1),
  'insight': ('D4', 1),
  'datum': ('D4', 1)},
 {'intuitively': ('D5', 1),
  'understand': (

In [87]:
title_indexing = reduce(
    join_dicts, 
    words
)

In [88]:
print(title_indexing['be'], "\n")
print(titles[12])

[('D0', 1), ('D12', 2), ('D13', 1), ('D14', 1), ('D15', 1), ('D18', 1), ('D36', 1), ('D56', 1), ('D57', 1), ('D58', 1), ('D60', 1), ('D61', 1), ('D83', 1), ('D86', 1), ('D87', 1), ('D98', 1), ('D108', 1), ('D113', 1), ('D121', 1), ('D123', 2), ('D128', 1), ('D136', 1), ('D138', 1), ('D139', 1), ('D140', 1), ('D153', 1), ('D169', 1), ('D170', 1), ('D216', 1), ('D218', 1), ('D224', 1), ('D227', 1), ('D231', 1), ('D233', 1), ('D237', 1), ('D246', 1), ('D258', 1), ('D261', 1), ('D264', 1), ('D267', 1), ('D273', 1), ('D321', 1), ('D330', 1), ('D335', 1)] 

deep learning be go to teach we all the lesson of our life job be for machine


### Předpokládaný výstup

```python
print(inverted_index['be'])
print(titles[12]) # zobrazení nadpisu pro kontrolu
```
```
[('D0', 1), ('D12', 2), ('D13', 1), ('D14', 1), ('D15', 1), ('D18', 1), ('D36', 1), ('D56', 1), ('D57', 1), ('D58', 1), ('D60', 1), ('D61', 1), ('D83', 1), ('D86', 1), ('D87', 1), ('D98', 1), ('D108', 1), ('D113', 1), ('D121', 1), ('D123', 2), ('D128', 1), ('D136', 1), ('D138', 1), ('D139', 1), ('D140', 1), ('D153', 1), ('D169', 1), ('D170', 1), ('D216', 1), ('D218', 1), ('D224', 1), ('D227', 1), ('D231', 1), ('D233', 1), ('D237', 1), ('D246', 1), ('D258', 1), ('D261', 1), ('D264', 1), ('D267', 1), ('D273', 1), ('D321', 1), ('D330', 1), ('D335', 1)]
```
deep learning be go to teach we all the lesson of our life job be for machine

Výstup bude identický za předpokladu použití spacy lemmatizéru. Zároveň výstup nemusí obsahovat stejný formát indexu, postačí *(index, count)*.